-- SELECT ContactName AS "Nome", Country AS "País",
-- (COUNT(*) -1) AS "Número de compatriotas" 
-- FROM w3schools.customers
-- GROUP BY ContactName, Country
-- HAVING COUNT(*) > 1
-- ORDER BY ContactName;
