SELECT T_JOB.JOB_TITLE AS Cargo,
MAX(T_EMP.SALARY) - MIN(T_EMP.SALARY) AS 'Variação Salarial',
ROUND(MIN(T_EMP.SALARY), 2) AS 'Média mínima mensal',
ROUND(MAX(T_EMP.SALARY), 2) AS 'Média máxima mensal'
FROM hr.jobs AS T_JOB
INNER JOIN hr.employees AS T_EMP
ON T_JOB.JOB_ID = T_EMP.JOB_ID
GROUP BY JOB_TITLE
ORDER BY MAX(T_EMP.SALARY) - MIN(T_EMP.SALARY), JOB_TITLE;
