SELECT DISTINCT J.JOB_TITLE AS 'Cargo',
  CASE
    WHEN J.MAX_SALARY BETWEEN 5000 AND 10000 THEN 'Baixo'
    WHEN J.MAX_SALARY BETWEEN 10001 AND 20000 THEN 'Médio'
    WHEN J.MAX_SALARY BETWEEN 20000 AND 30000 THEN 'Alto'
    ELSE 'Altíssimo'
  END AS 'Nível'
FROM jobs AS J
ORDER BY J.JOB_TITLE ASC;