USE hr;
DELIMITER $$

CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(EMAIL VARCHAR(100))
RETURNS INT READS SQL DATA
BEGIN
DECLARE QUANTIDADE INT;
SELECT COUNT(*)
FROM hr.job_history AS JH
INNER JOIN hr.employees AS E
ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.EMAIL = EMAIL
INTO QUANTIDADE;
RETURN QUANTIDADE;
END; $$

DELIMITER $$
