-- SELECT
-- J.JOB_TITLE AS 'Cargo',
-- (J.MAX_SALARY - J.MIN_SALARY) AS 'Variação Salarial',
-- @MIN := ROUND(AVG(J.MIN_SALARY), 2) AS 'Média mínima mensal',
-- @MAX := ROUND(AVG(J.MAX_SALARY), 2) AS 'Média máxima mensal'
-- FROM jobs AS J GROUP BY JOB_TITLE;