SELECT JOB_TITLE,
CASE
  WHEN MAX_SALARY <= 10000 THEN 'BAIXO'
  WHEN MAX_SALARY > 10000 AND MAX_SALARY <= 20000 THEN 'MÉDIO'
  WHEN MAX_SALARY > 20000 AND MAX_SALARY <= 30000 THEN 'ALTO'
  ELSE 'ALTÍSSIMO'
END AS 'Nível'
FROM hr.jobs
ORDER BY JOB_TITLE;
